name: previewer
channels:
  - conda-forge
  - pyviz
dependencies:
  - python>=3.6
  - gdal>=2.4
  - matplotlib
  - numpy
  - xarray
  - rioxarray
  - pygmt
  - pandas
  - scipy
  - panel
  - geoviews=1.9.5
  - cartopy
  - panel
  - holoviews=1.14.8
  - netCDF4
packages:
- jupyter-panel-proxy
